# Generated by Django 5.1.3 on 2024-11-27 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='The name assigned to this chat room.', help_text='The name of the chat room.', max_length=255, verbose_name='Room Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='The timestamp of when this room was created.', help_text='The date and time the room was created.', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy')], db_comment="Tracks the agent's current status: Online, Offline, or Busy.", default='offline', help_text='The current status of the agent.', max_length=10, verbose_name='Status')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_comment='The timestamp when the agent joined the chat support system.', help_text='The date and time the agent joined.', verbose_name='Joined At')),
                ('avatar', models.ImageField(db_comment='Stores the avatar image for the agent.', help_text='Upload an avatar for the agent. This will be displayed in the chat interface.', upload_to='avatars/')),
                ('user', models.OneToOneField(db_comment='Reference to the user who acts as an agent.', help_text='The user associated with this agent.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sage_Agent',
                'verbose_name_plural': 'Sage_Agents',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(db_comment='The actual text content of the message sent in the chat.', help_text='The content of the chat message.', verbose_name='Message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_comment='The date and time when this message was created.', help_text='The time this message was sent.', verbose_name='Timestamp')),
                ('agent', models.ForeignKey(blank=True, db_comment='References the agent who sent this message.', help_text='The agent who sent this message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='sage_ref.agent', verbose_name='Agent')),
                ('author', models.ForeignKey(db_comment='Reference to the user who created this message', help_text='The user who sent this message.', on_delete=django.db.models.deletion.CASCADE, related_name='user_chat', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('room', models.ForeignKey(db_comment='References the chat room this message belongs to.', help_text='The room where this message was sent.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sage_ref.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
            },
        ),
    ]
