# Generated by Django 5.1.3 on 2024-11-27 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_ref', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_key',
            field=models.CharField(blank=True, db_comment='The session key of the anonymous user (if not authenticated).', help_text='Session key for anonymous users.', max_length=255, null=True, verbose_name='Session Key'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(blank=True, db_comment='Reference to the user who created this message', help_text='The user who sent this message.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_chat', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
