# Generated by Django 5.1.3 on 2024-11-28 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_ref', '0002_chatmessage_session_key_alter_chatmessage_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(db_comment='Reference to the user who acts as an agent.', help_text='The user associated with this agent.', on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
